name = "FastTanhSinhQuadrature"
uuid = "b650e0df-f744-4436-b963-b44034668c57"
authors = ["Stamatis Vretinaris"]
version = "1.0.0-DEV"

[deps]
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.10"
